- name: Setup NGINX + PHP and deploy web page with OCI upload
  hosts: webservers
  become: true

  tasks:
    - name: Install NGINX and PHP
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nginx
        - php
        - php-cli
        - php-curl
        - unzip
        - curl

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Copy upload.php
      copy:
        src: files/upload.php
        dest: /var/www/html/upload.php
        mode: '0755'

    - name: Ensure OCI CLI is installed
      shell: |
        if ! command -v oci &> /dev/null; then
          curl -sL https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
        fi
      args:
        executable: /bin/bash
